<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GradeSeeder extends Seeder
{
    public function run()
    {
        DB::table('grades')->truncate();
        DB::table('grades')->insert([
       
    ['codtab' => '7061', 'name' => 'متصرف مستشار', 'namefr' => 'Administrateur conseiller'],
    ['codtab' => '7100', 'name' => 'متصرف رئيسي', 'namefr' => 'Administrateur principal'],
    ['codtab' => '7105', 'name' => 'متصرف', 'namefr' => 'Administrateur'],
    ['codtab' => '7103', 'name' => 'متصرف محلل', 'namefr' => 'Administrateur analyste'],
    ['codtab' => '7150', 'name' => 'ملحق رئيسي للإدارة', 'namefr' => 'Attaché principal d’administration'],
    ['codtab' => '7155', 'name' => 'ملحق الإدارة', 'namefr' => 'Attaché d’administration'],
    ['codtab' => '6100', 'name' => 'ملحق الإدارة', 'namefr' => 'Attaché d’administration'],
    ['codtab' => '7165', 'name' => 'عون إدارة رئيسي', 'namefr' => 'Agent principal d’administration'],
    ['codtab' => '4075', 'name' => 'عون إدارة رئيسي', 'namefr' => 'Agent principal d’administration'],
    ['codtab' => '7180', 'name' => 'عون إدارة', 'namefr' => 'Agent d’administration'],
    ['codtab' => '4140', 'name' => 'عون إدارة', 'namefr' => 'Agent d’administration'],
    ['codtab' => '6175', 'name' => 'عون مكتب', 'namefr' => 'Agent de bureau'],
    ['codtab' => '7200', 'name' => 'عون مكتب', 'namefr' => 'Agent de bureau'],
    ['codtab' => '4170', 'name' => 'عون حفظ البيانات', 'namefr' => 'Agent de saisie de données'],
    ['codtab' => '7185', 'name' => 'كاتب', 'namefr' => 'Secrétaire'],
    ['codtab' => '6141', 'name' => 'كاتب مديرية رئيسي', 'namefr' => 'Secrétaire principal de direction'],
    ['codtab' => '6140', 'name' => 'كاتب مديرية', 'namefr' => 'Secrétaire de direction'],
    ['codtab' => '7171', 'name' => 'محاسب إداري رئيسي', 'namefr' => 'Comptable administratif principal'],
    ['codtab' => '7175', 'name' => 'محاسب إداري', 'namefr' => 'Comptable administratif'],
    ['codtab' => '7190', 'name' => 'مساعد محاسب إداري', 'namefr' => 'Adjoint comptable administratif'],
    ['codtab' => '4074', 'name' => 'مساعد متصرف', 'namefr' => 'Adjoint administrateur'],
    ['codtab' => '7110', 'name' => 'مهندس دولة', 'namefr' => 'Ingénieur d’État'],
    ['codtab' => '7145', 'name' => 'تقني سام', 'namefr' => 'Technicien supérieur'],
    ['codtab' => '473', 'name' => 'مساعد مهندس مستوى 02', 'namefr' => 'Assistant ingénieur niveau 2'],
    ['codtab' => '6225', 'name' => 'وثائقي أمين المحفوظات', 'namefr' => 'Documentaliste-archiviste'],
    ['codtab' => '6064', 'name' => 'وثائقي أمين محفوظات رئيسي', 'namefr' => 'Documentaliste-archiviste principal'],
    ['codtab' => '6080', 'name' => 'مساعد وثائقي أمين محفوظات', 'namefr' => 'Adjoint documentaliste-archiviste'],
    ['codtab' => '6065', 'name' => 'مساعد وثائقي أمين محفوظات رئيسي', 'namefr' => 'Adjoint principal documentaliste-archiviste'],
    ['codtab' => '1020', 'name' => 'معلم مدرسة إبتدائية', 'namefr' => 'Instituteur (école primaire)'],
    ['codtab' => '1005', 'name' => 'أستاذ المدرسة الإبتدائية', 'namefr' => 'Professeur (école primaire)'],
    ['codtab' => '1000', 'name' => 'أستاذ رئيسي للمدرسة الإبتدائية', 'namefr' => 'Professeur principal (école primaire)'],
    ['codtab' => '1001', 'name' => 'أستاذ مكون في المدرسة الإبتدائية', 'namefr' => 'Formateur (école primaire)'],
    ['codtab' => '1008', 'name' => 'أستاذ التعليم الابتدائي', 'namefr' => 'Enseignant (enseignement primaire)'],
    ['codtab' => '1004', 'name' => 'أستاذ التعليم الابتدائي قسم أوَّل', 'namefr' => 'Enseignant primaire — 1re division'],
    ['codtab' => '1003', 'name' => 'أستاذ التعليم الابتدائي قسم ثانٍ', 'namefr' => 'Enseignant primaire — 2e division'],
    ['codtab' => '1002', 'name' => 'أستاذ مميز في التعليم الابتدائي', 'namefr' => 'Enseignant distingué (primaire)'],
    ['codtab' => '3020', 'name' => 'أستاذ التعليم الأساسي', 'namefr' => 'Professeur (enseignement fondamental)'],
    ['codtab' => '3005', 'name' => 'أستاذ التعليم المتوسط', 'namefr' => 'Professeur (enseignement moyen)'],
    ['codtab' => '3004', 'name' => 'أستاذ رئيسي للتعليم المتوسط', 'namefr' => 'Professeur principal (enseignement moyen)'],
    ['codtab' => '3001', 'name' => 'أستاذ مكون في التعليم المتوسط', 'namefr' => 'Formateur (enseignement moyen)'],
    ['codtab' => '3003', 'name' => 'أستاذ التعليم المتوسط قسم أوَّل', 'namefr' => 'Enseignant moyen — 1re division'],
    ['codtab' => '3002', 'name' => 'أستاذ التعليم المتوسط قسم ثانٍ', 'namefr' => 'Enseignant moyen — 2e division'],
    ['codtab' => '3000', 'name' => 'أستاذ مميز في التعليم المتوسط', 'namefr' => 'Enseignant distingué (moyen)'],
    ['codtab' => '5040', 'name' => 'أستاذ تقني في الثانوية رئيس أشغال', 'namefr' => 'Professeur technique (lycée) — chef des travaux'],
    ['codtab' => '5040', 'name' => 'أستاذ تقني في الثانوية رئيس ورشة', 'namefr' => 'Professeur technique (lycée) — chef d’atelier'],
    ['codtab' => '5020', 'name' => 'أستاذ التعليم الثانوي', 'namefr' => 'Professeur (enseignement secondaire)'],
    ['codtab' => '5007', 'name' => 'أستاذ رئيسي للتعليم الثانوي', 'namefr' => 'Professeur principal (secondaire)'],
    ['codtab' => '5006', 'name' => 'أستاذ مكون في التعليم الثانوي', 'namefr' => 'Formateur (enseignement secondaire)'],
    ['codtab' => '5010', 'name' => 'أستاذ مبرز', 'namefr' => 'Professeur émérite'],
    ['codtab' => '5008', 'name' => 'أستاذ التعليم الثانوي قسم أوَّل', 'namefr' => 'Enseignant secondaire — 1re division'],
    ['codtab' => '5004', 'name' => 'أستاذ التعليم الثانوي قسم ثانٍ', 'namefr' => 'Enseignant secondaire — 2e division'],
    ['codtab' => '5000', 'name' => 'أستاذ مميز في التعليم الثانوي', 'namefr' => 'Enseignant distingué (secondaire)'],
    ['codtab' => '4062', 'name' => 'مساعد رئيسي للتربية', 'namefr' => 'Adjoint principal de l’éducation'],
    ['codtab' => '4045', 'name' => 'مشرف التربية', 'namefr' => 'Superviseur de l’éducation'],
    ['codtab' => '4041', 'name' => 'مشرف رئيسي للتربية', 'namefr' => 'Superviseur principal de l’éducation'],
    ['codtab' => '4036', 'name' => 'مشرف رئيس التربية', 'namefr' => 'Chef superviseur de l’éducation'],
    ['codtab' => '4028', 'name' => 'مشرف العام للتربية', 'namefr' => 'Superviseur général de l’éducation'],
    ['codtab' => '404',  'name' => 'مشرف التربية في الإبتدائي', 'namefr' => 'Superviseur de l’éducation (primaire)'],
    ['codtab' => '2025', 'name' => 'مربي متخصص في الدعم التربوي', 'namefr' => 'Éducateur spécialisé en soutien pédagogique'],
    ['codtab' => '2020', 'name' => 'مربي متخصص رئيسي في الدعم التربوي', 'namefr' => 'Éducateur spécialisé principal (soutien pédagogique)'],
    ['codtab' => '2015', 'name' => 'مربي متخصص رئيس في الدعم التربوي', 'namefr' => 'Éducateur spécialisé chef (soutien pédagogique)'],
    ['codtab' => '2008', 'name' => 'مربي متخصص عام في الدعم التربوي', 'namefr' => 'Éducateur spécialisé général (soutien pédagogique)'],
    ['codtab' => '4030', 'name' => 'مستشار التربية', 'namefr' => 'Conseiller pédagogique'],
    ['codtab' => '4015', 'name' => 'مستشار رئيس للتربية', 'namefr' => 'Conseiller principal en éducation'],
    ['codtab' => '2006', 'name' => 'ناظر في التعليم الابتدائي', 'namefr' => 'Directeur (enseignement primaire)'],
    ['codtab' => '4006', 'name' => 'ناظر في التعليم المتوسط', 'namefr' => 'Directeur (collège)'],
    ['codtab' => '4002', 'name' => 'ناظر في التعليم الثانوي', 'namefr' => 'Directeur (lycée)'],
    ['codtab' => '6005', 'name' => 'ناظر ثانوية', 'namefr' => 'Directeur de lycée'],
    ['codtab' => '4035', 'name' => 'مستشار التوجيه و الإرشاد المدرسي و المهني', 'namefr' => 'Conseiller d’orientation scolaire et professionnelle'],
    ['codtab' => '4016', 'name' => 'مستشار رئيسي للتوجيه و الإرشاد المدرسي و المهني', 'namefr' => 'Conseiller principal d’orientation scolaire et professionnelle'],
    ['codtab' => '4029', 'name' => 'مستشار محلل للتوجيه و الإرشاد المدرسي و المهني', 'namefr' => 'Conseiller analyste en orientation scolaire et professionnelle'],
    ['codtab' => '4003', 'name' => 'مستشار رئيس للتوجيه و الإرشاد المدرسي و المهني', 'namefr' => 'Conseiller principal d’orientation scolaire et professionnelle'],
    ['codtab' => '4067', 'name' => 'ملحق بالمخابر', 'namefr' => 'Attaché de laboratoire'],
    ['codtab' => '4046', 'name' => 'ملحق رئيسي بالمخابر', 'namefr' => 'Attaché principal de laboratoire'],
    ['codtab' => '4043', 'name' => 'ملحق رئيس بالمخابر', 'namefr' => 'Attaché en chef de laboratoire'],
    ['codtab' => '4037', 'name' => 'ملحق مشرف بالمخابر', 'namefr' => 'Attaché superviseur de laboratoire'],
    ['codtab' => '7125', 'name' => 'مستشار التغذية المدرسية', 'namefr' => 'Conseiller en nutrition scolaire'],
    ['codtab' => '6165', 'name' => 'مساعد المصالح الإقتصادية', 'namefr' => 'Adjoint aux services économiques'],
    ['codtab' => '4065', 'name' => 'مساعد رئيسي للمصالح الإقتصادية', 'namefr' => 'Adjoint principal aux services économiques'],
    ['codtab' => '4060', 'name' => 'نائب مقتصد', 'namefr' => 'Adjoint intendant'],
    ['codtab' => '6055', 'name' => 'نائب مقتصد مسير', 'namefr' => 'Adjoint intendant gestionnaire'],
    ['codtab' => '4025', 'name' => 'مقتصد', 'namefr' => 'Intendant'],
    ['codtab' => '6010', 'name' => 'مقتصد رئيسي', 'namefr' => 'Intendant principal'],
    ['codtab' => '2010', 'name' => 'مساعد مدير المدرسة الإبتدائية', 'namefr' => 'Adjoint au directeur (école primaire)'],
    ['codtab' => '2004', 'name' => 'مدير المدرسة الإبتدائية', 'namefr' => 'Directeur (école primaire)'],
    ['codtab' => '4004', 'name' => 'مدير المتوسطة', 'namefr' => 'Directeur du collège'],
    ['codtab' => '4000', 'name' => 'مدير الثانوية', 'namefr' => 'Directeur du lycée'],
    ['codtab' => '7065', 'name' => 'مفتش التعليم الإبتدائي', 'namefr' => 'Inspecteur de l’enseignement primaire'],
    ['codtab' => '7085', 'name' => 'مفتش التغذية المدرسية', 'namefr' => 'Inspecteur de la nutrition scolaire'],
    ['codtab' => '7055', 'name' => 'مفتش التعليم المتوسط', 'namefr' => 'Inspecteur de l’enseignement moyen'],
    ['codtab' => '7050', 'name' => 'مفتش التربية الوطنية', 'namefr' => 'Inspecteur de l’éducation nationale'],
    ['codtab' => '7035', 'name' => 'مفتش التعليم الإبتدائي تخصص إدارة المدارس الابتدائية', 'namefr' => 'Inspecteur primaire — spécialité gestion des écoles primaires'],
    ['codtab' => '7030', 'name' => 'مفتش التعليم الإبتدائي  تخصص المواد', 'namefr' => 'Inspecteur primaire — spécialité matières'],
    ['codtab' => '7040', 'name' => 'مفتش التعليم الإبتدائي  تخصص التغذية المدرسية', 'namefr' => 'Inspecteur primaire — spécialité nutrition scolaire'],
    ['codtab' => '7020', 'name' => 'مفتش التعليم المتوسط تخصص إدارة المتوسطات', 'namefr' => 'Inspecteur moyen — spécialité gestion des collèges'],
    ['codtab' => '7015', 'name' => 'مفتش التعليم المتوسط تخصص المواد', 'namefr' => 'Inspecteur moyen — spécialité matières'],
    ['codtab' => '7046', 'name' => 'مفتش التعليم الثانوي تخصص إدارة الثانويات', 'namefr' => 'Inspecteur secondaire — spécialité gestion des lycées'],
    ['codtab' => '7045', 'name' => 'مفتش التعليم الثانوي تخصص المواد', 'namefr' => 'Inspecteur secondaire — spécialité matières'],
    ['codtab' => '4076', 'name' => 'عامل مهني خارج الصنف', 'namefr' => 'Ouvrier professionnel hors catégorie'],
    ['codtab' => '4120', 'name' => 'عامل مهني من الصنف الأول', 'namefr' => 'Ouvrier professionnel — catégorie 1'],
    ['codtab' => '6215', 'name' => 'عامل مهني من الصنف الثاني', 'namefr' => 'Ouvrier professionnel — catégorie 2'],
    ['codtab' => '4122', 'name' => 'عامل مهني من الصنف الثالث', 'namefr' => 'Ouvrier professionnel — catégorie 3'],
    ['codtab' => '6195', 'name' => 'سائق سيارة من الصنف الأول', 'namefr' => 'Chauffeur — catégorie 1'],
    ['codtab' => '6200', 'name' => 'سائق سيارة من الصنف الثاني', 'namefr' => 'Chauffeur — catégorie 2'],
    ['codtab' => '4156', 'name' => 'سائق سيارة من المستوى الثاني', 'namefr' => 'Chauffeur — niveau 2'],
    ['codtab' => 'B202', 'name' => 'سائق سيارة من المستوى الأول', 'namefr' => 'Chauffeur — niveau 1'],
    ['codtab' => 'A192', 'name' => 'عامل مهني من المستوى الأول توقيت كامل', 'namefr' => 'Ouvrier professionnel niveau 1 — temps plein'],
    ['codtab' => 'A162', 'name' => 'عامل مهني من المستوى الثاني توقيت كامل', 'namefr' => 'Ouvrier professionnel niveau 2 — temps plein'],
    ['codtab' => 'A122', 'name' => 'عامل مهني من المستوى الثالث توقيت كامل', 'namefr' => 'Ouvrier professionnel niveau 3 — temps plein'],
    ['codtab' => 'A120', 'name' => 'عامل مهني من المستوى الرابع توقيت كامل', 'namefr' => 'Ouvrier professionnel niveau 4 — temps plein'],
    ['codtab' => 'C218', 'name' => 'عامل مهني من المستوى الأول توقيت جزئي', 'namefr' => 'Ouvrier professionnel niveau 1 — temps partiel'],
    ['codtab' => 'R003', 'name' => 'عامل مهني من المستوى الثالث توقيت جزئي', 'namefr' => 'Ouvrier professionnel niveau 3 — temps partiel'],
    ['codtab' => 'R004', 'name' => 'عامل مهني من المستوى الرابع توقيت جزئي', 'namefr' => 'Ouvrier professionnel niveau 4 — temps partiel'],
    ['codtab' => 'C209', 'name' => 'عون الخدمة من المستوى الأول', 'namefr' => 'Agent de service — niveau 1'],
    ['codtab' => 'C210', 'name' => 'عون الخدمة من المستوى الثاني', 'namefr' => 'Agent de service — niveau 2'],
    ['codtab' => '7235', 'name' => 'عون الخدمة من المستوى الثاني-توقيت جزئي', 'namefr' => 'Agent de service niveau 2 — temps partiel'],
    ['codtab' => 'C212', 'name' => 'عون الخدمة من المستوى الثالث', 'namefr' => 'Agent de service — niveau 3'],
    ['codtab' => 'C211', 'name' => 'عون الخدمة من المستوى الثالث-توقيت جزئي', 'namefr' => 'Agent de service niveau 3 — temps partiel'],
    ['codtab' => 'B145', 'name' => 'مرافق الحياة المدرسية', 'namefr' => 'Animateur de la vie scolaire'],
    ['codtab' => '7213', 'name' => 'سائق سيارة من المستوى الثالث و رئيس حظيرة', 'namefr' => 'Chauffeur niveau 3 et chef de dépôt'],
    ['codtab' => 'B140', 'name' => 'عون الوقاية من المستوى الثاني', 'namefr' => 'Agent de prévention — niveau 2'],
    ['codtab' => 'A180', 'name' => 'عون الوقاية من المستوى الأول', 'namefr' => 'Agent de prévention — niveau 1'],
    ['codtab' => '7000', 'name' => ' مدير التربية', 'namefr' => 'Directeur de l’éducation'],
    ['codtab' => '6170', 'name' => 'كاتب', 'namefr' => 'Secrétaire'],
    ['codtab' => '5500', 'name' => 'أستاذ التعليم الثانوي', 'namefr' => 'Professeur (enseignement secondaire)'],
    ['codtab' => '7195', 'name' => 'عون حفظ البيانات', 'namefr' => 'Agent de saisie de données'],




        ]);
    }
}

